version: '3'

services:
  frontend:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    command: [nginx-debug, '-g', 'daemon off;']
  backend:
    build: .
    ports:
      - 8080:8080
